apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pvc-longhorn
  namespace: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 15Gi
